# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: pull_request

jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
    steps:

      # Runs a single command using the runners shell
      - name: Require Pull Request approvals
  # You may pin to the exact commit or the version.
  # uses: manuelmeister/require-approved-pull-request-action@902369d0610e0df39589eedcae3ab228d3a64a8d
        uses: manuelmeister/require-approved-pull-request-action@0.0.1
        with:
    # Token to authenticate with when connecting to Github
         id: srinivasareddy4218
    # Minimum approvals
         minimum_approvals: 1
         run: echo 'hai'
