name: manual approval

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
 job_without_approval:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script 
      run: echo hello >> job_output.txt
    
    - name: Upload job output artifact
      uses: actions/upload-artifact@v2
      with:
        name: job_output
        path: job_output.txt


