# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push

jobs:
  job1:
    runs-on: windows-latest
    steps:
     - uses: trstringer/manual-approval@v
       with:
          secret: ${{ github.TOKEN }}
          approvers: Trimukesh
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
