name: manual approval

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
 job_without_approval:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script 
      run: echo hello > job_output.txt
    - name: Upload job output artifact
      uses: actions/upload-artifact@v3
      with:
       name: job_output
       path: job_output.txt

 job_needs_approval:
    needs: job_without_approval
    runs-on: windows-latest
    steps:
      - name: Request manual approval
        uses: actions/github-script@v4
        with:
          script: |
            const { data: { html_url: url } } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Manual approval needed for workflow',
              head: context.sha,
              base: 'main',
              body: 'Please approve this workflow to continue.',
            });
            core.exportVariable('APPROVAL_URL', url);
      - name: Send email
        uses: maful/github-actions-mailgun@main
        with:
          from: ${{ secrets.FROM_EMAIL }}
          to: ${{ secrets.TO_EMAIL }}
          subject: 'Action subject'
          body: 'Action body'
          attachment: ${{ github.workspace }}/github.png

