name: manual approval

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Build app
        run: |
          # build steps go here

      - name: Manual approval
        id: approval
        uses: "peter-evans/wait-on@v2"
        with:
          resources: |
            http-get://localhost:8080
          timeout: "10m"

      - name: Deploy app
        if: steps.approval.outputs.result == 'success'
        run: |
          # deployment steps go here
