name: manual approval
# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
 job_without_approval:
  runs-on: self-hosted
  steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script 
      run: echo hello > job_output.txt
    - name: Upload job output artifact
      uses: actions/upload-artifact@v2
      with:
        name: job_output
        path: job_output.txt

 job_needs_approval:
  needs: job_without_approval
  runs-on: ubuntu-latest
  steps:
    - name: Request manual approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: srinivasareddy4218,steja6872
        minimum-approvals: 1
        exclude-workflow-initiator-as-approver: true
        issue-title: "Need approval to run this test job"
        issue-body: |
          The job without approval output:
          ```
          C:\Users\tpadala\actions-runner\actions-runner\actions-runner\_work\task4\task4
          ```
          Please review and approve the above output to proceed with the job.
    - name: Download job output artifact
      uses: actions/download-artifact@v2
      with:
        name: job_output
    - name: Run a multi-line script
      run: |
        echo "This job needs approvals to run"
        echo "After approving job will run"
