name: manual approval

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
 job_without_approval:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script 
      run: echo hello > job_output.txt
    - name: Upload job output artifact
      uses: actions/upload-artifact@v3
      with:
       name: job_output
       path: job_output.txt

 job_needs_approval:
    needs: job_without_approval
    runs-on: ubuntu-latest
    steps:
      - name: Request manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: srinivasareddy4218,steja6872
          minimum-approvals: 1
          email-to: srinivasareddy4218@gmail.com
          subject: "Need approval to run this test job"
          body: "The job without approval output is attached. Please review and approve the above output to proceed with the job."
          attachments: |
            job_output.txt
       
      - uses: actions/checkout@v1    
      - name: Run a multi-line script
        run: |
          echo "This job needs approvals to run"
          echo "After approving job will run"

