name: manual approval

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job doesn't require approval
  job_without_approval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script 
        id: job_without_approval
        run: echo hello > job_output.txt
        # Store the job output as a step output
        # to be used in the manual approval message
        # Note: outputs are only available to subsequent steps
        # in the same job or to dependent jobs
        # see: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idoutputs
        # 
        # The syntax to reference the output in the manual approval message is:
        # ${ { steps.job_without_approval.outputs.job_output } }
        # where 'job_without_approval' is the id of the job and 'job_output' is the name of the output
        # (in this case, 'job_output.txt')

  # This job requires approval
  job_needs_approval:
    needs: job_without_approval
    runs-on: ubuntu-latest
    steps:
      - name: Request manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: srinivasareddy4218, steja6872
          minimum-approvals: 1
          exclude-workflow-initiator-as-approver: true
          issue-title: "Need approval to run this test job"
          issue-body: |
            The job without approval output:
            ```
            ${ { steps.job_without_approval.outputs.job_output } }
            ```
            Please review and approve the above output to proceed with the job.

      - uses: actions/checkout@v1    
      - name: Run a multi-line script
        run: |
          echo "This job needs approvals to run"
          echo "After approving job will run"
