name: Manual Approval Workflow
on:
  push:
    branches:
      - main
jobs:


  test:
  
    runs-on: windows-latest
    steps:
      # Your test steps here
      - name: Wait for manual approval
        uses: actions/github-script@v4
        with:
          script: |
            const { data: { html_url: url } } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Manual approval needed for workflow',
              head: context.sha,
              base: 'main',
              body: 'Please approve this workflow to continue.',
            });
            core.exportVariable('APPROVAL_URL', url);

      - name: Notify approver
        uses: actions/github-script@v4
        with:
          script: |
            const url = process.env.APPROVAL_URL;
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: url.split('/').pop(),
              body: `@username Please approve this workflow by clicking [here](${url}).`,
            });

      # Your remaining steps here
